version: "3.7"

services:
  aliyun-ddns:
    build: ./
    image: aliyun-ddns:latest
    restart: always
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
